INSERT INTO account_title (account_title, account_code) VALUES ('Cash - Collecting Officers', '1010101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Petty Cash Fund', '1010102000');
INSERT INTO account_title (account_title, account_code) VALUES ('Cash in Bank - Local Currency, Current Account', '1010202024');
INSERT INTO account_title (account_title, account_code) VALUES ('Cash - National Treasury - MDS', '1010404000');
INSERT INTO account_title (account_title, account_code) VALUES ('Loans Receivables-Others', '1030101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Due from NGAs', '1030301000');
INSERT INTO account_title (account_title, account_code) VALUES ('Due from NGOs and POs', '1030303000');
INSERT INTO account_title (account_title, account_code) VALUES ('Receivables - Disallowance Charges', '1030501000');
INSERT INTO account_title (account_title, account_code) VALUES ('Due from Operating Units', '1030502000');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Receivables', '1030599000');
INSERT INTO account_title (account_title, account_code) VALUES ('Office Supplies Inventory', '1040401000');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Supplies Inventory', '1040499000');
INSERT INTO account_title (account_title, account_code) VALUES ('Machineries', '1060501000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accumulated Depreciation - Machineries', '1060501100');
INSERT INTO account_title (account_title, account_code) VALUES ('Office Equipment', '1060502000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accumulated Depreciation - Office Equipment', '1060502100');
INSERT INTO account_title (account_title, account_code) VALUES ('IT Equipment and Software', '1060503000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accumulated Depreciation - IT Equipment and Software', '1060503100');
INSERT INTO account_title (account_title, account_code) VALUES ('Communication Equipment', '1060507000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accumulated Depreciation - Communication Equipment', '1060507100');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Machineries and Equipment', '1060599000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accumulated Depreciation - Other Machineries & Equipt', '1060599100');
INSERT INTO account_title (account_title, account_code) VALUES ('Motor Vehicles', '1060601000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accumulated Depreciation - Motor Vehicles', '1060601100');
INSERT INTO account_title (account_title, account_code) VALUES ('Furniture and Fixtures', '1060701000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accumulated Depreciation - Furniture and Fixtures', '1060701100');
INSERT INTO account_title (account_title, account_code) VALUES ('Library Books', '1080103000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accumulated Depreciation - Library Books', '1080103100');
INSERT INTO account_title (account_title, account_code) VALUES ('Advances to Officers and Employees', '1990101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Prepaid Rent', '1990202000');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Assets', '1999999000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accounts Payables', '2010101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Due to Officers & Employees', '2010102000');
INSERT INTO account_title (account_title, account_code) VALUES ('Due to BIR', '2020101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Due to GSIS', '2020102000');
INSERT INTO account_title (account_title, account_code) VALUES ('Due to PAG-IBIG', '2020103000');
INSERT INTO account_title (account_title, account_code) VALUES ('Due to PHILHEALTH', '2020104000');
INSERT INTO account_title (account_title, account_code) VALUES ('Due to Central Office', '2030101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Payables', '2999999000');
INSERT INTO account_title (account_title, account_code) VALUES ('Government Equity', '3010101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Income and Expense Summary', '3030101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Permit Fees', '4020101099');
INSERT INTO account_title (account_title, account_code) VALUES ('Registration Fees', '4020102000');
INSERT INTO account_title (account_title, account_code) VALUES ('Clearance and Certification Fees', '4020104002');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Permits and Licenses', '4020107000');
INSERT INTO account_title (account_title, account_code) VALUES ('Processing Fees', '4020111001');
INSERT INTO account_title (account_title, account_code) VALUES ('Fines and Penalties - Service Income ', '4020114000');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Service Income ', '4020199099');
INSERT INTO account_title (account_title, account_code) VALUES ('Subsidy Income from National Government', '4030101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Gain/Loss on Sale of Disposed Asset', '4050104000');
INSERT INTO account_title (account_title, account_code) VALUES ('Salaries and Wages - Regular Pay', '5010101001');
INSERT INTO account_title (account_title, account_code) VALUES ('Salaries and Wages - Contractual', '5010102000');
INSERT INTO account_title (account_title, account_code) VALUES ('Personal Economic Relief Allowance (PERA)', '5010201001');
INSERT INTO account_title (account_title, account_code) VALUES ('Representation Allowance (RA)', '5010202000');
INSERT INTO account_title (account_title, account_code) VALUES ('Transportation Allowance (TA)', '5010203001');
INSERT INTO account_title (account_title, account_code) VALUES ('Clothing/Uniform Allowance', '5010204001');
INSERT INTO account_title (account_title, account_code) VALUES ('Productivity Incentive Benefits', '5010208001');
INSERT INTO account_title (account_title, account_code) VALUES ('Longevity Pay', '5010212001');
INSERT INTO account_title (account_title, account_code) VALUES ('Year-End Bonus', '5010214001');
INSERT INTO account_title (account_title, account_code) VALUES ('Cash Gift', '5010215001');
INSERT INTO account_title (account_title, account_code) VALUES ('Life and Retirement Insurance Contributions', '5010301000');
INSERT INTO account_title (account_title, account_code) VALUES ('PAG-IBIG Contributions', '5010302001');
INSERT INTO account_title (account_title, account_code) VALUES ('PHILHEALTH Contributions', '5010303001');
INSERT INTO account_title (account_title, account_code) VALUES ('ECC Contributions', '5010304001');
INSERT INTO account_title (account_title, account_code) VALUES ('Terminal Leave Credits', '5010403001');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Personal Benefits', '5010499099');
INSERT INTO account_title (account_title, account_code) VALUES ('Travelling Expenses - Local', '5020101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Traveling Expenses - Foreign', '5020102000');
INSERT INTO account_title (account_title, account_code) VALUES ('Training Expenses', '5020201000');
INSERT INTO account_title (account_title, account_code) VALUES ('Office Supplies Expenses', '5020301000');
INSERT INTO account_title (account_title, account_code) VALUES ('Accountable Forms Expenses', '5020302000');
INSERT INTO account_title (account_title, account_code) VALUES ('Gasoline, Oil And Lubricants Expense', '5020309000');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Supplies Expenses', '5020399000');
INSERT INTO account_title (account_title, account_code) VALUES ('Water Expenses', '5020401000');
INSERT INTO account_title (account_title, account_code) VALUES ('Electricity Expenses', '5020402000');
INSERT INTO account_title (account_title, account_code) VALUES ('Postage and Deliveries', '5020501000');
INSERT INTO account_title (account_title, account_code) VALUES ('Telephone Expenses - Landline', '5020502001');
INSERT INTO account_title (account_title, account_code) VALUES ('Internet Expenses', '5020503000');
INSERT INTO account_title (account_title, account_code) VALUES ('Cable, Satellite, Telegraph and Radio Expenses', '5020504000');
INSERT INTO account_title (account_title, account_code) VALUES ('Extraordinary Expenses', '5021003000');
INSERT INTO account_title (account_title, account_code) VALUES ('Legal Services', '5021101000');
INSERT INTO account_title (account_title, account_code) VALUES ('Auditing Services', '5021102000');
INSERT INTO account_title (account_title, account_code) VALUES ('Consultancy Services', '5021103000');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Professional Services', '5021199000');
INSERT INTO account_title (account_title, account_code) VALUES ('Janitorial Services', '5021202000');
INSERT INTO account_title (account_title, account_code) VALUES ('Security Services', '5021203000');
INSERT INTO account_title (account_title, account_code) VALUES ('General Services', '5021299000');
INSERT INTO account_title (account_title, account_code) VALUES ('Repairs and Maintenance - Office Equipment', '5021305000');
INSERT INTO account_title (account_title, account_code) VALUES ('Repairs and Maintenance - Motor Vehicles', '5021306001');
INSERT INTO account_title (account_title, account_code) VALUES ('Repairs and Maintenance - Furniture and Fixtures', '5021307000');
INSERT INTO account_title (account_title, account_code) VALUES ('Leasehold Improvements', '5021309002');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Subsidies', '5021403000');
INSERT INTO account_title (account_title, account_code) VALUES ('Taxes, Duties and Licenses', '5021501001');
INSERT INTO account_title (account_title, account_code) VALUES ('Fidelity Bond Premium', '5021502000');
INSERT INTO account_title (account_title, account_code) VALUES ('Insurance Expenses', '5021503000');
INSERT INTO account_title (account_title, account_code) VALUES ('Advertising Expenses', '5029901000');
INSERT INTO account_title (account_title, account_code) VALUES ('Printing and Binding Expenses', '5029902000');
INSERT INTO account_title (account_title, account_code) VALUES ('Representation Expenses', '5029903000');
INSERT INTO account_title (account_title, account_code) VALUES ('Transportation and Delivery Expenses', '5029904000');
INSERT INTO account_title (account_title, account_code) VALUES ('Rent Expenses', '5029905001');
INSERT INTO account_title (account_title, account_code) VALUES ('Subsciptions Expenses', '5029907000');
INSERT INTO account_title (account_title, account_code) VALUES ('Other Maintenance and Operating Expenses', '5029999002');
INSERT INTO account_title (account_title, account_code) VALUES ('Bank Charges', '5030104000');
INSERT INTO account_title (account_title, account_code) VALUES ('Depreciation - Office Equipment', '5050105000');
INSERT INTO account_title (account_title, account_code) VALUES ('Depreciation - Motor Vehicles', '5050106001');
INSERT INTO account_title (account_title, account_code) VALUES ('Depreciation - Furniture and Fixtures', '5050107000');
INSERT INTO account_title (account_title, account_code) VALUES ('Depreciation-Other Asset', '5050199099');
INSERT INTO account_title (account_title, account_code) VALUES ('Documentary Stamp Expenses', '5050399000');
INSERT INTO account_title (account_title, account_code) VALUES ('Prior Years Adjustments', '5050409000');